version: "3.8"

networks:
        mtbAI:

services:
         python:
                build:
                        dockerfile: Dockerfile
                command:
                  - --gpus
                  - all
                  - nvidia/cuda:11.4.0-base-ubuntu20.04
                  - nvidia-smi
                container_name: mtb_AI
                restart: "no"
                ports:
                        - "51001:22"
                volumes:
                        - /nextcloud/data:/home/dev/data # symlink to mount /nextcloud/data to /data on container
